Preconditions.checkArgument problematic in pivotal :
```
2016-11-19T18:48:05.99+0700 [APP/PROC/WEB/0]OUT Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.quikdo.core.PlaceRepository]: Factory method 'placeRepo' threw exception; nested exception is java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
```